### ISSUE TITLE
Assigned Specifications (AKA Todo list)

### ISSUE THREAD

**Issue by TheBurnerGuy** [TheBurnerGuy/291F17MP#1]
Pick two. (Example: - [ ] Do Thing - Henry) 
- [x] Search for Products - Henry
- [ ] Place an order - Jordan
- [x] List orders - Calvin
- [x] Set up a delivery - Henry
- [x] Update a delivery - Henry
- [x] Add to stock - Calvin
The login specification and implementation should be done collaboratively (because it includes an extra feature for size 3 groups!)
